# Example workflow for automatically pushing flag changes to your provider
# when PRs are merged to your default branch
#
# To use this in your project:
# 1. Copy this file to .github/workflows/ in your repository
# 2. Update the remote-url to your flag provider's API endpoint
# 3. Add your auth token as a secret named FLAGD_STUDIO_TOKEN (or update the secret name)
# 4. Optionally customize the manifest-path if your flags file is not flags.json

name: Auto-Push Flags

on:
  push:
    branches:
      - main  # Or your default branch
    paths:
      - 'flags.json'  # Only trigger when flags file changes
      # Add more paths if you have multiple flag files
      # - 'flags/*.json'

jobs:
  push-to-provider:
    name: Push to Flag Provider
    uses: open-feature/action/.github/workflows/push-on-merge.yml@main
    with:
      manifest-path: 'flags.json'
      remote-url: 'https://flagd-studio.onrender.com/api'  # Your provider URL
      # branch: main  # Optional: defaults to your default branch
      # cli-version: latest  # Optional: specify a specific CLI version
      # dry-run: false  # Optional: set to true to test without pushing
    secrets:
      auth-token: ${{ secrets.FLAGD_STUDIO_TOKEN }}  # Your provider auth token

  # IMPORTANT: Notify team if push fails after merge
  notify-on-failure:
    name: Notify on Failure
    needs: push-to-provider
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify team via Slack
        uses: slackapi/slack-github-action@v1
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}  # Add your Slack webhook as a secret
          payload: |
            {
              "text": "🚨 Flag Push Failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Automated flag push failed after merge*\n\n• *Repository:* ${{ github.repository }}\n• *Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>\n• *Author:* @${{ github.actor }}\n\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow run>"
                  }
                }
              ]
            }
      # Alternative: Create a GitHub issue instead
      # - name: Create issue on failure
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       await github.rest.issues.create({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         title: '🚨 Automated flag push failed',
      #         body: `The automated flag push failed. [View run](${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
      #         labels: ['flag-sync', 'urgent']
      #       });

# Alternative: Multiple manifest files
# If you have multiple flag manifests, you can push them all:
#
# jobs:
#   push-production-flags:
#     uses: open-feature/action/.github/workflows/push-on-merge.yml@main
#     with:
#       manifest-path: 'flags/production.json'
#       remote-url: 'https://prod.flag-provider.com/api'
#     secrets:
#       auth-token: ${{ secrets.PROD_FLAG_TOKEN }}
#
#   push-staging-flags:
#     uses: open-feature/action/.github/workflows/push-on-merge.yml@main
#     with:
#       manifest-path: 'flags/staging.json'
#       remote-url: 'https://staging.flag-provider.com/api'
#     secrets:
#       auth-token: ${{ secrets.STAGING_FLAG_TOKEN }}